/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SidebarItem({ icon, text, isActive }) {
  return (
    <div
      className={`flex overflow-hidden flex-col justify-center items-start py-2 w-full rounded-md ${
        isActive ? "bg-black bg-opacity-50" : ""
      } max-w-[212px]`}
    >
      <div className="flex gap-2 items-center pl-2">
        {typeof icon === "string" ? (
          <div className="self-stretch p-1 my-auto w-6 text-sm font-bold">
            {icon}
          </div>
        ) : (
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          />
        )}
        <button className="self-stretch my-auto text-base">{text}</button>
      </div>
    </div>
  );
}

export default SidebarItem;
