/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";

const sidebarItems = [
  { icon: "􀎭", 
    text: "Home", 
    isActive: true 
  },
  {
    icon: "􀎭",
    text: "Dashboard",
  },
  {
    icon: "􀎭",
    text: "Alert",
  },
  {
    icon: "􀎭",
    text: "Chat",
  },
  {
    icon: "􀎭",
    text: "File",
  },
  {
    icon: "􀎭",
    text: "System Center",
  },
];

function Sidebar() {
  return (
    <nav className="flex overflow-hidden flex-col max-w-[251px] bg-[#7B579A] bg-opacity-80">
      <div className="flex overflow-hidden flex-col items-start pt-14 pr-7 pl-2.5 w-full pb-[548px]">
        <div className="flex flex-col self-stretch tracking-wide text-white whitespace-nowrap">
          {sidebarItems.map((item, index) => (
            <SidebarItem key={index} {...item} />
          ))}
        </div>
      </div>
    </nav>
  );
}

export default Sidebar;
