/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex overflow-hidden flex-wrap gap-5 justify-between items-start px-6 py-3 w-full text-xs font-medium text-center whitespace-nowrap bg-slate-800 max-md:px-5 max-md:max-w-full">
      <div className="flex gap-2">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8531baff16ead942c5eb111985a918aaba0e2b376a28e5ea6f777993bb072952?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
          alt=""
          className="object-contain shrink-0 rounded-none aspect-[1.39] w-[25px]"
        />
        <div className="px-7 pt-px pb-2 rounded-3xl max-md:px-5">FIG-121</div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/dfd83caae73f5bed3e1618e6da327ee4f4c1888d7678cc254d0065f974a34581?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
        alt=""
        className="object-contain shrink-0 self-stretch max-w-full rounded-none aspect-[5.29] w-[106px]"
      />
      <div className="flex gap-2.5">
        <button className="flex gap-1 px-3 py-0.5 rounded-3xl bg-stone-900 bg-opacity-30 shadow-[0px_4px_4px_rgba(0,0,0,0.25)]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/85e5838a487ebc01c6384a54c3f888c53852ae2643aee593d558cd727671a157?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
            alt=""
            className="object-contain shrink-0 self-start aspect-square w-[13px]"
          />
          <span>PDF</span>
        </button>
        <button className="flex gap-1 px-3 py-1 rounded-3xl bg-stone-900 bg-opacity-30">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d45f0b70cbcc0d72ed3a0e43d0e907792646d575f8cc393a1780f15e1aeaf584?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
            alt=""
            className="object-contain shrink-0 self-start w-2.5 aspect-square"
          />
          <span>Help</span>
        </button>
      </div>
    </header>
  );
}

export default Header;
