/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Summary from "./Summary";
import ChatInput from "./ChatInput";

function Chatpage() {
  return (
    <main className="flex overflow-hidden flex-col text-white ">
      <div className="flex flex-col px-1 h-screen w-screen bg-[#1d203e] max-md:max-w-full">
        <Header />
        <section className="flex flex-col justify-center items-center px-20 py-11 max-md:px-5 max-md:max-w-full">
          <div className="flex flex-col w-full max-w-[765px] max-md:max-w-full">
            <Summary />
          </div>
          <div className="flex flex-col w-full max-w-[765px] max-md:max-w-full absolute insert-x-0 bottom-10 ">
        <ChatInput />
        </div>
        </section>
        
      </div>
    </main>
  );
}

export default Chatpage;
