/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Summary() {
  return (
    <article className="flex flex-col px-8 py-6 w-full rounded-3xl max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between mr-3 w-full max-md:mr-2.5 max-md:max-w-full">
        <div className="flex gap-3">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/eee8e6c76ed6bf6d117a2f0c912c05bcd3b648b281aea4b3f2c4aba71bac4bb9?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
            alt=""
            className="object-contain shrink-0 aspect-square rounded-[30px] w-[41px]"
          />
          <div className="flex flex-col my-auto">
            <h2 className="text-xs font-bold">SUMMARY</h2>
            <p className="self-start mt-2 text-xs font-medium">
              Power by OpenAI
            </p>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/dc88d54b7de616c9cddbbc81fd85d2beabce7441758ca9a74292faecfb0c1239?placeholderIfAbsent=true&apiKey=bae4f78d557141349e757a6705679bd5"
          alt=""
          className="object-contain shrink-0 my-auto w-3.5 aspect-[0.87]"
        />
      </div>
      <hr className="shrink-0 mt-3 h-0 border border-solid border-neutral-400 max-md:max-w-full" />
      <div className="mt-3.5 mr-5 ml-6 text-xs font-bold max-md:mr-2.5 max-md:max-w-full">
        <h3 className="text-xl">Incident FIG-121 Assessment</h3>
        <h4 className="text-base">Summary</h4>
        <p className="font-light">
          Incident 29088, titled "SAP - (Preview) File Downloaded From a
          Malicious IP Address," involves a high severity event where a user
          downloaded a file from an SAP system using a malicious IP address. The
          incident is related to the "Exfiltration" tactic and is currently in
          "New" status.
        </p>
        <h4 className="text-base">Entities Involved</h4>
        <p className="font-light">
          The entities involved in this incident are:
        </p>
        <ul className="font-light list-disc list-inside">
          <li>Host CPC-mscot-SOCOS (Windows)</li>
          <li>IP: 185.82.217.3</li>
          <li>Account: mscott@woodgrovems (AzureAD)</li>
        </ul>
        <h4 className="text-base">Supporting Evidence</h4>
        <p className="font-light">
          The IP address 185.82.217.3 has a reputation score of 100, classifying
          it as malicious. It is associated with known cyber threat intelligence
          profiles, such as Cobalt Strike an Silk Typhoon, and has exhibited
          suspicious behavior.
        </p>
        <h4 className="text-base">Confidence Level</h4>
        <p className="font-light">
          Based on the available evidence, the confidence level in the
          assessment of this incident is high.
        </p>
        <h4 className="text-base">Recommendations</h4>
        <ol className="font-light list-decimal list-inside">
          <li>
            Investigate the user's activities and the file downloaded from the
            malicious IP address to determine if any sensitive data was
            exfiltrated or if the user's account was compromised.
          </li>
          <li>
            Review the security policies and access controls for the user and
            their devices to ensure they are in line with the organization's
            security requirements.
          </li>
        </ol>
      </div>
    </article>
  );
}

export default Summary;
